### ISSUE TITLE
Query box doesn't have proper width

### ISSUE THREAD

**Issue by masad-frost** [amasad/eHistory#13]
http://i.imgur.com/RvkSiTb.jpg

Edit: Probably because of this https://github.com/amasad/eHistory/commit/d77f8cce6365cb9ea3721046af6c3567101c68cd

Another quick edit: 

`width: calc(100% - 16px);` is giving "invalid property value"

**Comment by masad-frost** [comment]
Adding `width: -webkit-calc(100% - 16px);` should solve it.

I'm having issues with SSH and can't commit

**Comment by amasad** [comment]
Interesting, this works fine on Chrome on Mac. It's probably a Windows only bug where maybe Chrome version is behind. This happens because when browsers implement a part of the CSS spec that isn't finalized they put it behind what is called a "vendor prefix" so if the spec changes at the last minute they can implement the finalized spec without breaking everyone using the older version (which was vendor prefixed). `-webkit-` for Safari/Chrome and other webkit-based browsers, `-moz-` for mozilla, `-o-` for Opera etc.

I'll wait for the pull request. Check github help on this, maybe start here: https://help.github.com/articles/set-up-git
