### ISSUE TITLE
can't click on local file links

### ISSUE THREAD

**Issue by isaacl** [amasad/eHistory#5]
eHistory doesn't allow me to click on local html pages listed in my history.  For example, I downloaded:

http://reduction.process.googlepages.com/example-final.html

and viewed it locally.  This shows up in eHistory but when I try to click on the link nothing happens and javascript console records

> Not allowed to load local resource: file://[....]

**Comment by amasad** [comment]
Thanks, looks valid.
Well look into it ASAP.

**Comment by amasad** [comment]
The problem here is that chrome blocks both websites and extensions to link to local files for security reasons. What I've done is that setup an alert to let you know that you can right-click open in new tab when you click on a local file link in eHistory.

Thanks a lot for reporting this, and I'm sorry this took way too long
